#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const D = p => path.join(__dirname, '..', p);

const edges = JSON.parse(fs.readFileSync(D('data/mechanisms/edges.json')));
const existing = new Set(edges.map(e=>e.id));

const batch = [
  { id: 'collective_trauma__franklin_roosevelt',
    source: 'collective_trauma', target: 'franklin_roosevelt', type: 'ENABLED',
    label: "FDR's New Deal mobilized collective trauma of the Depression for transformation",
    note: "The Great Depression was a collective trauma that Roosevelt successfully mobilized as political energy for institutional transformation. The New Deal was possible because collective trauma made Americans receptive to radical government intervention — channeling the trauma into reform rather than demagogic scapegoating.",
    confidence: 'high' },
  { id: 'moral_disengagement__harry_truman',
    source: 'moral_disengagement', target: 'harry_truman', type: 'ENABLED',
    label: "Truman's atomic bomb decisions exemplify moral disengagement at scale",
    note: "The decision to drop atomic bombs on Hiroshima and Nagasaki required abstracting 200,000 civilian deaths into strategic calculus. The institutionalization of large-scale civilian targeting as legitimate military strategy required systematic moral disengagement at organizational and individual levels.",
    confidence: 'high' },
  { id: 'institutional_credibility_laundering__dwight_eisenhower',
    source: 'institutional_credibility_laundering', target: 'dwight_eisenhower', type: 'ENABLED',
    label: "Eisenhower warned that military-industrial credibility laundering threatened democracy",
    note: "Eisenhower's military-industrial complex warning (1961) identified institutional credibility laundering: private defense contractors using military prestige to advance commercial interests, acquiring unwarranted influence over policy through the borrowed authority of the military institution.",
    confidence: 'high' },
  { id: 'collective_trauma__jawaharlal_nehru',
    source: 'collective_trauma', target: 'jawaharlal_nehru', type: 'ENABLED',
    label: "Nehru's non-alignment emerged from the collective trauma of colonial subordination",
    note: "Nehru's non-alignment policy emerged from the collective trauma of British colonialism and the Partition. Indian independence required building a national identity that could hold together diverse ethnic, religious, and linguistic groups — an identity built partly on shared colonial trauma and its negation.",
    confidence: 'high' },
  { id: 'social_contract_theory__code_of_hammurabi',
    source: 'social_contract_theory', target: 'code_of_hammurabi', type: 'ENABLED',
    label: "Hammurabi's Code is the earliest systematic statement of law as governance contract",
    note: "Hammurabi's Code (c.1754 BCE) represents the earliest comprehensive legal code: laws applying to all subjects, with a prologue stating Hammurabi's divine mandate to make justice prevail. This is a proto-social contract: authority is legitimate insofar as it serves justice, not merely power.",
    confidence: 'medium' },
  { id: 'social_contract_theory__athenian_democracy',
    source: 'social_contract_theory', target: 'athenian_democracy', type: 'ENABLED',
    label: "Athenian democracy was the first institutional instantiation of consent-based governance",
    note: "Athenian democracy (c.508 BCE) is the first institutional form of the idea that legitimate governance requires citizen participation. Its radical limitation — excluding women, slaves, and foreigners — also makes it the paradigm case of how consent of the governed coexists with systematic exclusion.",
    confidence: 'high' },
  { id: 'social_contract_theory__peace_of_westphalia',
    source: 'social_contract_theory', target: 'peace_of_westphalia', type: 'ENABLED',
    label: "Westphalia established state sovereignty as the foundation of international order",
    note: "The Peace of Westphalia (1648) created the modern state system: sovereign states with recognized territorial boundaries as the primary actors. This established the international social contract — mutual recognition of sovereignty — that underlies all subsequent international law.",
    confidence: 'high' },
  { id: 'structural_violence__mandate_system',
    source: 'structural_violence', target: 'mandate_system', type: 'ENABLED',
    label: "League of Nations mandates institutionalized structural violence as liberal imperialism",
    note: "The mandate system created a hierarchy of territories administered by colonial powers under the legal fiction of developing them toward self-governance. The mandates that mattered were assigned to powers with strategic interests, embedding structural violence into the post-WWI international order.",
    confidence: 'high' },
  { id: 'dehumanization__herero_nama_genocide',
    source: 'dehumanization', target: 'herero_nama_genocide', type: 'ENABLED',
    label: "German colonial dehumanization enabled the first 20th-century genocide",
    note: "The Herero and Nama genocide (1904-08) was enabled by colonial dehumanization: German colonists defined the Herero as subhuman Untermenschen whose extermination was pest control. General von Trotha's extermination order was the logical conclusion of colonial dehumanization ideology, directly influencing Nazi racial thinking.",
    confidence: 'high' },
  { id: 'collective_trauma__herero_nama_genocide',
    source: 'collective_trauma', target: 'herero_nama_genocide', type: 'CAUSED',
    label: "The Herero genocide produced collective trauma transmitted across generations",
    note: "The genocide destroyed approximately 80% of the Herero population, producing collective trauma that shaped Namibian national identity and the century-long campaign for German reparations (recognized 2021). The long-delayed acknowledgment demonstrates how collective trauma without recognition persists.",
    confidence: 'high' },
  { id: 'structural_violence__buck_v_bell',
    source: 'structural_violence', target: 'buck_v_bell', type: 'ENABLED',
    label: "Buck v. Bell inscribed compulsory sterilization into constitutional law",
    note: "Buck v. Bell (1927) gave constitutional authority to compulsory sterilization programs. The decision has never been formally overturned, sitting in US law as institutionalized structural violence. Oliver Wendell Holmes' 'Three generations of imbeciles are enough' epitomizes structural violence laundered through judicial authority.",
    confidence: 'high' },
  { id: 'in_group_out_group_dynamics__english_reformation',
    source: 'in_group_out_group_dynamics', target: 'english_reformation', type: 'ENABLED',
    label: "The English Reformation created Protestant/Catholic in-group conflict with lasting effects",
    note: "Henry VIII's English Reformation created confessional in-group/out-group boundaries producing: Thomas More's execution, dissolution of monasteries, Mary's persecutions, and the sectarian conflict persisting in Northern Ireland. The religious split was entangled with dynastic succession and property redistribution.",
    confidence: 'high' },
  { id: 'collective_trauma__battle_of_stalingrad',
    source: 'collective_trauma', target: 'battle_of_stalingrad', type: 'CAUSED',
    label: "Stalingrad produced collective trauma shaping Soviet and German national identity",
    note: "The Battle of Stalingrad (1942-43) — 2 million total casualties — became the defining collective trauma of WWII for both Soviet and German populations. For the USSR it was the turning point; for Germany the moral recognition that the war was lost and the regime's promises were lies.",
    confidence: 'high' },
  { id: 'dehumanization__battle_of_stalingrad',
    source: 'dehumanization', target: 'battle_of_stalingrad', type: 'ENABLED',
    label: "Both sides deployed dehumanization to sustain fighting in extreme conditions",
    note: "Stalingrad's extreme conditions required maximum dehumanization. Soviet propaganda portrayed German soldiers as fascist beasts; Nazi ideology had already dehumanized Soviet people as Untermenschen. Dehumanization was the psychological infrastructure enabling combat under conditions that would otherwise trigger breakdown.",
    confidence: 'high' },
  { id: 'in_group_out_group_dynamics__sunni_shia_split',
    source: 'in_group_out_group_dynamics', target: 'sunni_shia_split', type: 'ENABLED',
    label: "The Sunni-Shia split is the foundational in-group/out-group fracture of Islamic civilization",
    note: "The question of Ali's succession (632 CE) created Islam's primary confessional fracture. Over fourteen centuries this theological dispute has been activated by political actors who found communal identity useful for mobilization. The Iran-Saudi Arabia proxy conflict is the contemporary expression of this ancient dynamic.",
    confidence: 'high' },
  { id: 'collective_trauma__sunni_shia_split',
    source: 'collective_trauma', target: 'sunni_shia_split', type: 'SHARES_MECHANISM_WITH',
    label: "Karbala is the foundational collective trauma of Shia identity",
    note: "The Battle of Karbala (680 CE) — the killing of Hussein ibn Ali — is the constitutive collective trauma of Shia Islam, annually re-enacted in Ashura. Collective trauma becomes identity: the Shia sense of persecution and martyrdom is built on transmission of this historical trauma across generations.",
    confidence: 'high' },
  { id: 'in_group_out_group_dynamics__september_11_attacks',
    source: 'in_group_out_group_dynamics', target: 'september_11_attacks', type: 'ENABLED',
    label: "September 11 triggered mass in-group/out-group reconfiguration",
    note: "September 11 produced an immediate, massive reconfiguration of in-group/out-group dynamics. Muslims and Arab-Americans became an out-group; American identity was redefined around a traumatic in-group boundary. This reconfiguration enabled the Iraq War, surveillance expansion, and ongoing Islamophobia — all predictable from in-group/out-group activation.",
    confidence: 'high' },
  { id: 'collective_trauma__september_11_attacks',
    source: 'collective_trauma', target: 'september_11_attacks', type: 'CAUSED',
    label: "September 11 produced collective trauma structuring two decades of US policy",
    note: "The September 11 attacks are the clearest recent example of collective trauma transmission: a shared catastrophic experience that produced lasting psychological, political, and institutional effects. The trauma structured the post-9/11 surveillance state, two wars, and security theater that outlasted the immediate threat.",
    confidence: 'high' },
  { id: 'israel_palestine_conflict__balfour_declaration',
    source: 'israel_palestine_conflict', target: 'balfour_declaration', type: 'ENABLED',
    label: "The Balfour Declaration is the originating document of the Israel-Palestine conflict",
    note: "The Balfour Declaration (1917) — a national home for Jewish people in Palestine while not prejudicing the rights of existing non-Jewish communities — created the structural contradiction generating the ongoing conflict. The impossibility of fulfilling both promises is built into the document itself.",
    confidence: 'high' },
  { id: 'structural_violence__sykes_picot_agreement',
    source: 'structural_violence', target: 'sykes_picot_agreement', type: 'ENABLED',
    label: "Sykes-Picot embedded structural violence into the modern Middle East",
    note: "The Sykes-Picot Agreement (1916) divided the Middle East drawing borders that cut across ethnic, religious, and tribal communities. The borders created minority-majority configurations requiring violent suppression to maintain — structural violence embedded in the territorial definition of states.",
    confidence: 'high' },
  { id: 'wahhabism_salafism__osama_bin_laden',
    source: 'wahhabism_salafism', target: 'osama_bin_laden', type: 'ENABLED',
    label: "Wahhabism provided the theological framework for bin Laden's jihadism",
    note: "Bin Laden was shaped by Wahhabi theology and Qutb's radical extension: the concept of takfir (declaring other Muslims apostates) and the obligation of offensive jihad. Without Saudi-funded global expansion of Wahhabi theology, the Al-Qaeda ideological formation is unintelligible.",
    confidence: 'high' },
  { id: 'radicalization_pipeline__osama_bin_laden',
    source: 'radicalization_pipeline', target: 'osama_bin_laden', type: 'ENABLED',
    label: "Bin Laden operated a physical radicalization pipeline through Afghanistan",
    note: "The Afghan training camps (1980s-2001) were a physical radicalization pipeline: young Muslim men with grievances were recruited, indoctrinated in Wahhabi-jihadist theology, trained militarily, and deployed globally. This physical pipeline prefigures the digital radicalization pipeline; the mechanism is identical.",
    confidence: 'high' },
  { id: 'oil_geopolitics__gamal_nasser',
    source: 'oil_geopolitics', target: 'gamal_nasser', type: 'ENABLED',
    label: "Nasser's nationalization of the Suez Canal reshaped oil geopolitics",
    note: "Nasser's 1956 Suez Canal nationalization challenged Western control of Middle Eastern energy infrastructure, triggering the Suez Crisis. His pan-Arab nationalism demonstrated that resource nationalism could succeed against colonial powers, influencing subsequent nationalizations in Libya, Iraq, and Iran.",
    confidence: 'high' },
  { id: 'dehumanization__genghis_khan',
    source: 'dehumanization', target: 'genghis_khan', type: 'ENABLED',
    label: "Mongol strategic terror required the conditional dehumanization of resisting populations",
    note: "Mongol strategic terror — deliberate massacre of cities that resisted — required dehumanization of enemy populations as obstacles to be eliminated. Cities that submitted were spared; cities that resisted were destroyed. The conditional dehumanization was itself the terror mechanism: populations heard of atrocities and calculated submission.",
    confidence: 'high' },
  { id: 'in_group_out_group_dynamics__martin_luther',
    source: 'in_group_out_group_dynamics', target: 'martin_luther', type: 'ENABLED',
    label: "Luther's Reformation hardened confessional in-group boundaries with lethal consequences",
    note: "Luther's Reformation created new confessional in-group/out-group structures that shaped European politics for two centuries: the Thirty Years' War, the St. Bartholomew's Day Massacre, and population transfers structured by cuius regio, eius religio. The same in-group/out-group mechanism, now with doctrinal content.",
    confidence: 'high' },
  { id: 'cultural_hegemony__paul_of_tarsus',
    source: 'cultural_hegemony', target: 'paul_of_tarsus', type: 'ENABLED',
    label: "Paul transformed a Jewish sect into the architecture of Western cultural hegemony",
    note: "Paul's theological innovations — the gentile mission, faith over works, universal salvation — were the organizational decisions transforming a Jewish reform movement into a universal religion. His letters established the cultural and doctrinal architecture that enabled Christianity to become, via Constantine, the hegemonic culture of Western civilization.",
    confidence: 'high' },
  { id: 'in_group_out_group_dynamics__jesus_of_nazareth',
    source: 'in_group_out_group_dynamics', target: 'jesus_of_nazareth', type: 'ENABLED',
    label: "Jesus systematically challenged in-group/out-group boundaries in his teaching",
    note: "Jesus' teachings repeatedly violated in-group/out-group boundaries: healing Samaritans and Romans, eating with tax collectors, the Good Samaritan parable. The early Christian community's dissolution of ethnic distinctions ('neither Jew nor Greek, slave nor free') was a direct extension of this challenge to inherited group boundaries.",
    confidence: 'high' },
  { id: 'in_group_out_group_dynamics__muhammad_ibn_abdallah',
    source: 'in_group_out_group_dynamics', target: 'muhammad_ibn_abdallah', type: 'ENABLED',
    label: "Muhammad created a new in-group (umma) that superseded tribal identity",
    note: "Muhammad's Constitution of Medina replaced tribal in-group (clan loyalty as primary) with the umma (Muslim community as primary in-group) — a radical restructuring of in-group/out-group dynamics enabling a multi-tribal political community. This reconstitution of in-group boundaries was the mechanism of early Islamic expansion.",
    confidence: 'high' },
  { id: 'in_group_out_group_dynamics__winston_churchill',
    source: 'in_group_out_group_dynamics', target: 'winston_churchill', type: 'ENABLED',
    label: "Churchill's colonial in-group/out-group views enabled imperial atrocities",
    note: "Churchill's explicit racial hierarchy — his views of Indians as 'beastly,' his blocking of Bengal famine relief (1943, killing 3+ million) — reflects in-group/out-group dynamics at imperial scale. The same person who resisted Hitler applied similar logic to colonized peoples, revealing that anti-fascism and colonial racism were psychologically compatible.",
    confidence: 'high' },
  { id: 'preference_falsification__nikita_khrushchev',
    source: 'preference_falsification', target: 'nikita_khrushchev', type: 'ENABLED',
    label: "Khrushchev's Secret Speech revealed the scale of Stalinist preference falsification",
    note: "Khrushchev's 1956 Secret Speech denouncing Stalin revealed how extensively preference falsification had operated: party members who privately doubted Stalinist claims had publicly applauded them for decades. The speech was a mass preference revelation event that shocked the international communist movement.",
    confidence: 'high' },
  { id: 'structural_violence__harriet_tubman',
    source: 'structural_violence', target: 'harriet_tubman', type: 'ENABLED',
    label: "Tubman navigated and actively resisted structural violence embedded in American law",
    note: "Tubman's Underground Railroad operated against the structural violence of the Fugitive Slave Act and the entire legal apparatus of slavery. Her resistance demonstrates that structural violence is not unchangeable: organized collective action can create exit routes even when the legal structure makes escape criminal.",
    confidence: 'high' },
  { id: 'in_group_out_group_dynamics__saladin',
    source: 'in_group_out_group_dynamics', target: 'saladin', type: 'ENABLED',
    label: "Saladin unified fractured Muslim in-groups against Crusader out-groups",
    note: "Saladin's political achievement was unifying the fractured Muslim world against the Crusader out-group, making the Crusader presence the dominant in-group/out-group frame that subordinated inter-Muslim conflicts. His magnanimity after victory deliberately contrasted with the Crusaders' 1099 massacre.",
    confidence: 'high' },
  { id: 'democratic_backsliding__church_committee',
    source: 'democratic_backsliding', target: 'church_committee', type: 'ENABLED',
    label: "The Church Committee documented systematic democratic backsliding in US intelligence",
    note: "The Church Committee (1975-76) documented CIA COINTELPRO, NSA domestic surveillance, and assassination plots — systematic violations of democratic norms by the intelligence apparatus. Its reforms (FISA courts, intelligence oversight) were the institutional response to demonstrated democratic backsliding.",
    confidence: 'high' },
  { id: 'collective_trauma__iranian_revolution_1979',
    source: 'collective_trauma', target: 'iranian_revolution_1979', type: 'ENABLED',
    label: "The Iranian Revolution channeled collective trauma of the Mossadegh coup and SAVAK",
    note: "The 1979 revolution channeled the collective trauma of the 1953 CIA coup that removed Mossadegh, decades of SAVAK torture, and the humiliations of US-backed Pahlavi modernization that felt like cultural colonization. Khomeini successfully mobilized this collective trauma as revolutionary energy.",
    confidence: 'high' },
  { id: 'cultural_hegemony__charles_darwin',
    source: 'cultural_hegemony', target: 'charles_darwin', type: 'SHARES_MECHANISM_WITH',
    label: "Social Darwinism misappropriated Darwin to naturalize class and racial hierarchy",
    note: "Darwin's evolution theory was rapidly misappropriated into Social Darwinism — applying natural selection to human society to naturalize class hierarchy, racial hierarchy, and imperial competition. Darwin himself resisted some extensions. The misappropriation shows how scientific authority can be captured for ideological hegemony.",
    confidence: 'high' },
  { id: 'dehumanization__joseph_stalin',
    source: 'dehumanization', target: 'joseph_stalin', type: 'ENABLED',
    label: "Stalinist purges deployed class-based dehumanization as liquidation mechanism",
    note: "Stalin's purges required systematic dehumanization: kulaks as class enemies deserving extermination, Trotskyites as subhuman wreckers, national minorities as inherently treacherous. The ideological dehumanization preceded and enabled the physical liquidation — Great Terror, collectivization famine, deportations.",
    confidence: 'high' },
  { id: 'dehumanization__heinrich_himmler',
    source: 'dehumanization', target: 'heinrich_himmler', type: 'ENABLED',
    label: "Himmler industrialized dehumanization as bureaucratic management",
    note: "Himmler's SS was the organizational embodiment of dehumanization as bureaucratic system: mass murder through paperwork, industrial processes, and organizational hierarchy. Himmler himself avoided witnessing murders — the bureaucratic disembodiment of killing is the purest form of moral disengagement-through-dehumanization.",
    confidence: 'high' },
  { id: 'dehumanization__pol_pot',
    source: 'dehumanization', target: 'pol_pot', type: 'ENABLED',
    label: "Khmer Rouge ideology dehumanized intellectuals, urbanites, and ethnic minorities",
    note: "The Khmer Rouge's Year Zero ideology systematically dehumanized educated people, urban dwellers, and ethnic Vietnamese as incompatible with agrarian utopia. Glasses marked one as an intellectual deserving execution. Dehumanization enabled a genocide that killed 25% of Cambodia's population.",
    confidence: 'high' },
  { id: 'structural_violence__leopold_ii_belgium',
    source: 'structural_violence', target: 'leopold_ii_belgium', type: 'ENABLED',
    label: "Leopold's Congo Free State was structural violence institutionalized as private enterprise",
    note: "Leopold's Congo (1885-1908) was structural violence in its purest corporate form: a privately held territory where the infrastructure (Force Publique, rubber quotas, hand-severing enforcement) was systematically designed for maximum profit through violence. Approximately 10 million Congolese died. The structural design required no individual sadism — only compliance.",
    confidence: 'high' },
];

let added = 0;
for (const e of batch) {
  if (!existing.has(e.id)) { edges.push(e); existing.add(e.id); added++; }
}
require('fs').writeFileSync(D('data/mechanisms/edges.json'), JSON.stringify(edges, null, 2));
console.log('Added:', added);
console.log('Total mechanism edges:', edges.length);

// Integrity
const allIds = new Set();
const scopes = ['mechanisms','global/media','global/health','global/psychology','global/politics','global/history'];
for (const s of scopes) JSON.parse(require('fs').readFileSync(D('data/'+s+'/nodes.json'))).forEach(n => allIds.add(n.id));
let orphans = 0;
for (const e of edges) {
  if (!allIds.has(e.source)) { console.log('ORPHAN src:', e.source); orphans++; }
  if (!allIds.has(e.target)) { console.log('ORPHAN tgt:', e.target); orphans++; }
}
console.log('Orphans:', orphans);
